### ISSUE TITLE
[REQUEST] Добавить возможность реализации подмены reqpath перед отправкой в Prometheus

### ISSUE THREAD

**Issue by eatenko** [MobileTeleSystems/botview#1]
Доброго времени суток.

Есть ли возможность реализовать функционал по замене reqPath перед отправкой в Prometheus.
Идет сильный спам и нагрузка в/на Prometheus за счет большого количества страниц.

Пример реализации на Go есть в проекте на github prometheus-nginxlog-exporter (match - relable)

Заранее спасибо

**Comment by LabEG** [comment]
Привет!

А речь точно о Prometheus? Потому что в него попадают только метрики рантайма и не попадают метрики запросов.
По запросам есть только логи.

Возможно в прометеуз засылает ваше приложение если там есть такие метрики.
